#!/bin/bash
set -e

if [ -n "${DATE_STYLE}" ]
then
    echo "==> Setting datestyle to ${DATE_STYLE}"
    sed -i "s/iso, mdy/iso, $(echo "${DATE_STYLE}")/g" /var/lib/postgresql/data/postgresql.conf
    pg_ctl reload
    echo "    Done"
fi

POSTGRES="psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

if [ -z "${APPLICATION_USER_1}" ]
then
    APPLICATION_USER_1=${APPLICATION_ROLE}_1
fi

if [ -z "${APPLICATION_USER_1_PWD}" ]
then
    APPLICATION_USER_1_PWD=${POSTGRES_PASSWORD}
fi

if [ -z "${SCHEMA_READ_ROLE}" ]
then
    SCHEMA_READ_ROLE=${SCHEMA}_read
fi

echo "==> Revoking create on public schema from public"
$POSTGRES <<-EOSQL
  REVOKE CREATE ON SCHEMA PUBLIC FROM PUBLIC;
EOSQL

echo "==> Revoking create on public schema from ${POSTGRES_USER} user"
$POSTGRES <<-EOSQL
  REVOKE CREATE ON SCHEMA PUBLIC FROM ${POSTGRES_USER};
EOSQL

echo "==> Revoking all privileges on ${POSTGRES_DB} database from public"
$POSTGRES <<-EOSQL
  REVOKE ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} FROM PUBLIC;
EOSQL

echo "==> Creating schema ${SCHEMA}"
$POSTGRES <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS ${SCHEMA} AUTHORIZATION ${POSTGRES_USER}
EOSQL

echo "==> Create ${APPLICATION_ROLE} role and grant connect privilege"
$POSTGRES <<-EOSQL
  CREATE ROLE ${APPLICATION_ROLE};
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APPLICATION_ROLE};
EOSQL

echo "==> Create ${SCHEMA_READ_ROLE} and grant connect privilege"
$POSTGRES <<-EOSQL
  CREATE ROLE ${SCHEMA_READ_ROLE};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${SCHEMA_READ_ROLE} IN SCHEMA ${SCHEMA} GRANT SELECT ON TABLES TO ${SCHEMA_READ_ROLE};
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${SCHEMA}_read;
EOSQL

echo "==> Create ${APPLICATION_USER_1} user"
$POSTGRES <<-EOSQL
  CREATE ROLE ${APPLICATION_USER_1}
  LOGIN PASSWORD '${APPLICATION_USER_1_PWD}'
  IN ROLE ${APPLICATION_ROLE};
EOSQL

echo "==> Grant usage on schema ${SCHEMA} to ${APPLICATION_ROLE} and ${SCHEMA_READ_ROLE}"
$POSTGRES <<-EOSQL
  GRANT USAGE ON SCHEMA ${SCHEMA} TO ${APPLICATION_ROLE};
  GRANT USAGE ON SCHEMA ${SCHEMA} TO ${SCHEMA_READ_ROLE};
EOSQL

echo "==> Set the search path for ${SCHEMA_READ_ROLE}, ${APPLICATION_ROLE} and ${POSTGRES_USER} roles/ users"
$POSTGRES <<-EOSQL
  ALTER ROLE ${POSTGRES_USER} SET search_path TO ${SCHEMA};
  ALTER ROLE ${APPLICATION_ROLE} SET search_path TO ${SCHEMA};
  ALTER ROLE ${APPLICATION_USER_1} SET search_path TO ${SCHEMA};
  ALTER ROLE ${SCHEMA_READ_ROLE} SET search_path TO ${SCHEMA};
EOSQL
